# Generated by Django 5.1.4 on 2024-12-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon_user_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentbookmodel',
            name='time',
        ),
        migrations.AlterField(
            model_name='appointmentbookmodel',
            name='date',
            field=models.DateTimeField(help_text='The date and time of the appointment.'),
        ),
    ]
