# Generated by Django 5.1.4 on 2024-12-23 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon_user_app', '0002_remove_appointmentbookmodel_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentbookmodel',
            name='appointment_exempted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointmentbookmodel',
            name='appointment_padding',
            field=models.DurationField(default=datetime.timedelta(seconds=2700)),
        ),
    ]
