# Generated by Django 5.1.4 on 2024-12-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon_user_app', '0003_appointmentbookmodel_appointment_exempted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentbookmodel',
            name='appointment_exempted',
        ),
        migrations.RemoveField(
            model_name='appointmentbookmodel',
            name='appointment_padding',
        ),
        migrations.AddField(
            model_name='appointmentbookmodel',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=100),
        ),
    ]
