# Generated by Django 5.1.4 on 2024-12-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon_admin_app', '0003_service_created_at_service_updated_at_and_more'),
        ('salon_user_app', '0004_remove_appointmentbookmodel_appointment_exempted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentbookmodel',
            name='service',
        ),
        migrations.AddField(
            model_name='appointmentbookmodel',
            name='remark',
            field=models.TextField(blank=True, help_text='Additional comments or notes for the appointment.', null=True),
        ),
        migrations.AddField(
            model_name='appointmentbookmodel',
            name='services',
            field=models.ManyToManyField(related_name='appointments', to='salon_admin_app.service'),
        ),
        migrations.AlterField(
            model_name='appointmentbookmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=100),
        ),
    ]
