# Generated by Django 5.1.4 on 2025-01-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon_user_app', '0006_customermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
