# Generated by Django 5.1.4 on 2025-01-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon_user_app', '0007_alter_customermodel_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='phone',
            field=models.CharField(default=1234567890, max_length=15),
            preserve_default=False,
        ),
    ]
