# Generated by Django 5.1.4 on 2025-01-06 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon_user_app', '0009_customermodel_profile_pic'),
    ]

    operations = [
        # migrations.AddField(
            # model_name='appointmentbookmodel',
            # name='customer',
            # field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='salon_user_app.customermodel'),
            # preserve_default=False,
        # ),
    ]
