# Generated by Django 5.1.4 on 2025-01-06 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon_user_app', '0010_appointmentbookmodel_customer'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='appointmentbookmodel',
        #     name='customer',
        # ),
    ]
