# Generated by Django 5.1.4 on 2025-01-06 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon_user_app', '0011_remove_appointmentbookmodel_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentbookmodel',
            name='customer',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='salon_user_app.customermodel'),
            preserve_default=False,
        ),
    ]
